server:
  port: 18188
spring:
  application:
    name: order
  rabbitmq:
    host: 192.168.211.132
    port: 5672
    username: guest
    password: guest
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/changgou_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.211.132
    port: 6379
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

#hystrix 配置  信号量隔离 防止新的线程调用(上次线程数据丢失)
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 100000000
          strategy: SEMAPHORE

mq:
  pay:
    exchange:
      order: exchange.order
      atonceorderexchange: atoncexchange.atonceorder
    queue:
      order: queue.order
      atonceorderqueue: atoncequeue.atonceorder
    routing:
      key: queue.order
      atoncekey: atoncequeue.atonceorder
#微信支付信息配置
weixin:
  #应用ID
  appid: wx8397f8696b538317
  #商户ID
  partner: 1473426802
  #秘钥(签名)
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  #支付回调地址
  notifyurl: http://266g98330k.qicp.vip:25171/weixin/pay//notify/url