server:
  port: 18092
spring:
  application:
    name: seckill
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/changgou_seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.211.132 #mq的服务器地址
    username: guest #账号
    password: guest #密码
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.211.132
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 100000000
          strategy: SEMAPHORE
mq:
  pay:
    exchange:
      order: exchange.order
      seckillorder: seckillexchange.seckillorder
    queue:
      order: queue.order
      seckillorder: seckillqueue.seckillorder
    routing:
      key: queue.order
      seckillkey: seckillqueue.seckillorder
      delayroutingkey:  orderSeckillDelayQueue   # 延时队列的队列名(可以作为routingKey)
#微信支付信息配置
weixin:
  #应用ID
  appid: wx8397f8696b538317
  #商户ID
  partner: 1473426802
  #秘钥(签名)
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb