server:
  port: 18093
spring:
  application:
    name: pay
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.211.132
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
#开启Feign的熔断:默认是线程池隔离
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 100000000
          strategy: SEMAPHORE

#微信支付信息配置
weixin:
  #应用ID
  appid: wx8397f8696b538317
  #商户ID
  partner: 1473426802
  #秘钥
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  #支付回调地址
  notifyurl: http://266g98330k.qicp.vip:25171/weixin/pay//notify/url
mq:
  pay:
    exchange:
      order: exchange.order
      seckillorder: seckillexchange.seckillorder
    queue:
      order: queue.order
      seckillorder: seckillqueue.seckillorder
    routing:
      key: queue.order
      seckillkey: seckillqueue.seckillorder